-   **Scraping del índice de criminalidad**

```{r}
library(rvest)

linkToWebIDE="https://es.numbeo.com/criminalidad/clasificaciones-por-pa%C3%ADs?title=2020"
xpathToTableIDE='//*[@id="t2"]'
ide <- read_html(linkToWebIDE)%>%html_nodes(xpath = xpathToTableIDE)%>%html_table()%>% .[[1]]
```

```{r}
colnames(ide) = c("Puesto","Pais","ic","is")
```

```{r}
ide$Puesto<- NULL
ide$is<- NULL
str(ide)
```

```{r}
gsub(',',".",ide$ic)
```

```{r}
ide$Countrycode=c('VEN', 'PNG', 'ZAF', 'AFG', 'HND', 'TTO', 'BRA', 'PER', 'SLV', 'GUY', 'NAM', 'SYR', 'JAM', 'PRI', 'AGO', 'BGD', 'NGA', 'BHS', 'LBY', 'KAZ', 'ARG', 'KEN', 'DOM', 'UGA', 'TZA', 'FJI', 'MYS', 'SOM', 'MNG', 'GTM', 'ZWE', 'CRI', 'COL', 'MEX', 'URY', 'BWA', 'MDV', 'BOL', 'ECU', 'KHM', 'DZA', 'PRY', 'IRN', 'ETH', 'GHA', 'UKR', 'MAR', 'IRQ', 'MUS', 'USA', 'PAN', 'SWE', 'EGY', 'FRA', 'BRM', 'IDN', 'IRL', 'VNM', 'CHL', 'MDA', 'NIC', 'ITA', 'PAK', 'BEL', 'GBR', 'PSE', 'LBN', 'IND', 'BIH', 'PHL', 'TUN', 'AUS', 'MNE', 'RUS', 'NZL', 'JOR', 'THA', 'GRC', 'LKA', 'CAN', 'ALB', 'TUR', 'MLT', 'MKD', 'BGR', 'SRB', 'LVA', 'NOR', 'HUN', 'DEU', 'KWT', 'NPL', 'LUX', 'LTU', 'XKX', 'ESP', 'CHI', 'AZE', 'SGP', 'CYP', 'PRT', 'ISR', 'BAR', 'SVK', 'POL', 'PRK', 'BRN', 'ROU', 'NDL', 'CUB', 'SAU', 'CZE', 'DNK', 'BLR', 'HRV', 'AUT', 'ISL', 'FIN', 'EST', 'ARM', 'CHE', 'SVN', 'OMN', 'HKG', 'JPN', 'GEO', 'ARE', 'TWN', 'QAT')
```

[**Empezando el merge**]{.underline}

-   *Importación de data*

```{r}
library(rio)
persesco=import("bmpersev.xls")
pobla=import("pobactu.xls")
gedu=import("gastoeduactu.xlsx")
nada=import("ningunactu.xlsx")
```

```{r}
pobla$'Country Name'<- NULL
persesco$'Country Name'<- NULL
```

-   *merge pobla y persesco*

```{r}
test1 = merge(pobla,persesco, by.x ="Country Code", by.y ="Country Code", all.x = T)
```

-   *merge test1 con gedu*

```{r}
gedu$'Country Name'<- NULL
```

```{r}
test2 = merge(test1,gedu, by.x ="Country Code", by.y ="Country Code", all.x = T)
```

-   *merge test2 con ide*

```{r}
ide$'Pais'<- NULL
```

```{r}
test3 = merge(test2,ide, by.x ="Country Code", by.y ="Countrycode", all.x = T)
```

-   *merge test3 con nada*

```{r}
nada$'Pais'<- NULL
```

```{r}
finaldata = merge(test3,nada, by.x ="Country Code", by.y ="Country Code", all.x = T)
```

-   *eliminar NA*

```{r}
datafinal <- finaldata [complete.cases (finaldata),]
finaldata
```
